export default {
    // FONTS
    FONT_SIZE_SMALL: 10,
    FONT_SIZE_SLIGHT_MEDIUM: 12,
    FONT_SIZE_MEDIUM: 14,
    FONT_SIZE_SLIGHT_LARGE: 16,
    FONT_SIZE_LARGE: 20,
    FONT_SIZE_X_LARGE: 25,

    FONT_LIGHT:  'ProximaNova-Light',
    FONT_REGULAR: 'ProximaNova-Regular',
    FONT_SEMIBOLD: 'ProximaNova-Semibold',
    FONT_BOLD: 'ProximaNova-Bold',
    FONT_BLACK: 'ProximaNova-Black',

    // COLORS
    COLOR_PURPLE: '#7A54F7',
    COLOR_BLUE: '#16D2FA',
    COLOR_YELLOW: '#F6DF5E',
    COLOR_GREEN: '#0CD59E',
    COLOR_RED: '#EE3861',
    COLOR_ORANGE: '#F77E54',
    COLOR_WHITE: '#F9F9F9',
    COLOR_BLACK: '#232323',
    COLOR_GRAY: '#9E9E9E',
    COLOR_LIGHT_GRAY: '#E5E5E5',

    // SPACING
    SPACING_SMALL: 10,
    SPACING_SLIGHT_MEDIUM: 18,
    SPACING_MEDIUM: 20,
    SPACING_LARGE: 50,

    BOTTOM_SCROLLVIEW_SPACING: 125,

    LETTER_SPACING_LARGE: 3,
    LETTER_SPACING_SMALL: 1,

    // ELEVATION
    CARD_ELEVATION: 10,
  };